name: Android CI Latest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set variables
      run: |
        VER=$(cat beta.md | head -n1 | sed -e "s/# //")
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cook KeyStore
      run:  echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks

    - name: Enable Reports
      run: sed "s/DisabledReports=true/DisabledReports=false/g" -i app/src/main/java/ani/saikou/others/DisabledReports.kt

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
        -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks 
        -Pandroid.injected.signing.store.password=${{ secrets.PASSWORD }} 
        -Pandroid.injected.signing.key.alias=key0
        -Pandroid.injected.signing.key.password=${{ secrets.PASSWORD }}
      shell: bash

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: "app/build/outputs/apk/debug/app-debug.apk"